### ISSUE TITLE
New home env var check fails by default on linux

### ISSUE THREAD

**Issue by P4sca1** [northwood-studios/LocalAdmin-V2#52] opened 2022-12-26 10:24 UTC
`Environment.GetFolderPath` returns an empty string, when the path does not exist.
According to https://jimrich.sk/environment-specialfolder-on-windows-linux-and-os-x/ `System.Environment.SpecialFolder.ApplicationData` resolves to `/home/{user}/.config`, which is a directory that does not exist by default (at least on ubuntu).

**Comment by zabszk** [comment] 2022-12-26 18:02
I have just tested it on clean Ubuntu 2020.04 LTS and Debian 11 installations and it's not the case. It doesn't return an empty string if the path doesn't exist.

Many SCP:SL communities (including our official ones) run LocalAdmin in Docker containers, where the .config folder doesn't exist and it was never an issue for anyone either.

**Comment by P4sca1** [comment] 2022-12-26 18:41
Weird, I started to get the error `can't obtain a valid user home directory path` recently. It was fixed after I created the `.config` folder manually. I'm running from a docker container based on Ubuntu 22.04. The env variable `HOME=home/myuser` is set.

**Comment by zabszk** [comment] 2022-12-26 18:45
Interesting issue. I will retest it on Ubuntu 22.04 LTS then.

If you run it in docker (presumably using pterodactyl), adding a command to create that path shouldn't be an issue as a temporary workaround.

**Comment by P4sca1** [comment] 2022-12-26 20:25
I am using my own docker image from https://GitHub.com/ips-hosting/game-images and did just that to fix the issue. Maybe one of my other command line arguments was causing the issue.

**Comment by J-Stuff** [comment] 2022-12-31 13:00
Testing with Ed_PlayZ. This issue is occouring on clean installs of Ubuntu.
![image](https://user-images.githubusercontent.com/68690676/210137086-4ed311ad-9417-4475-8746-bf12343b56ac.png)

https://nextcloud.j-stuff.net/s/Hinb9SHmNKefBx8

It requires a .config directory to be created manually by the user in the home directory of the host user to remove the error.

**Comment by zabszk** [comment] 2022-12-31 16:06
I can't reproduce the issue (even on a clean installation of Ubuntu 2020.04 LTS), but I made a PR that should fix this bug.

**Comment by zabszk** [comment] 2022-12-31 16:10
@P4sca1 @J-Stuff Can you test the build from PR (https://github.com/northwood-studios/LocalAdmin-V2/suites/10123726988/artifacts/494040544)? I can't reproduce the issue.

**Comment by EdPlayZ** [comment] 2022-12-31 21:17
@zabszk seems to be fixed in that one.

**Comment by J-Stuff** [comment] 2022-12-31 21:22
Fixed in the test build!
https://nextcloud.j-stuff.net/s/9aEBJHrPTsp9ayx

**Comment by zabszk** [comment] 2022-12-31 21:31
> Fixed in the test build! https://nextcloud.j-stuff.net/s/9aEBJHrPTsp9ayx

Thanks for testing.

**Closed** 2022-12-31 21:32 UTC
